# Generated by Django 4.2.1 on 2023-06-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_title_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
