# Generated by Django 4.2.1 on 2023-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='descriptioon',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
