# Generated by Django 4.2.1 on 2023-06-26 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 26, 11, 28, 4, 159077, tzinfo=datetime.timezone.utc)),
        ),
    ]
