# Generated by Django 4.2.1 on 2023-06-26 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
