# Generated by Django 4.2.1 on 2023-06-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_new_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
