# Generated by Django 4.2.1 on 2023-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_newcategorie_alter_new_category_delete_newcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='history_images')),
                ('history_title', models.CharField(blank=True, max_length=200)),
                ('history_description', models.TextField()),
                ('history_image', models.ImageField(upload_to='history_images')),
            ],
        ),
    ]
